import { Hono } from "hono";
import type { GatewayBindings } from "@arch/cloudflare-bindings";
import type { GatewayVariables } from "./types";
import { adminRoutes } from "./routes/admin.routes";
import { authRoutes } from "./routes/auth.routes";
import { catalogRoutes } from "./routes/catalog.routes";
import { ledgerRoutes } from "./routes/ledger.routes";
import { orderRoutes } from "./routes/order.routes";
import { storefrontRoutes } from "./routes/storefront.routes";
import { vendorRoutes } from "./routes/vendor.routes";
import { proxyToService } from "./utils/proxy";
import { clerkAuthGuard } from "./middleware/clerk-auth-guard";
import { rateLimiter } from "./middleware/rate-limiter";
import { requestLogger } from "./middleware/request-logger";
import { sentryMiddleware } from "./middleware/sentry-middleware";
import { tenantResolver } from "./middleware/tenant-resolver";

export const createGatewayRouter = (): Hono<{ Bindings: GatewayBindings; Variables: GatewayVariables }> => {
  const router = new Hono<{ Bindings: GatewayBindings; Variables: GatewayVariables }>();
  router.use("*", requestLogger, tenantResolver, rateLimiter, sentryMiddleware);
  // Health endpoints bypass auth
  router.get("/catalog/health", async (c) => proxyToService(c, c.env.CATALOG_WORKER, "/catalog"));
  router.get("/orders/health", async (c) => proxyToService(c, c.env.ORDER_WORKER, "/orders"));
  router.get("/vendors/health", async (c) => proxyToService(c, c.env.VENDOR_WORKER, "/vendors"));
  router.get("/admin/health", async (c) => proxyToService(c, c.env.TENANT_WORKER, "/admin"));
  router.get("/ledger/health", async (c) => proxyToService(c, c.env.LEDGER_WORKER, "/ledger"));
  router.use("/catalog/*", clerkAuthGuard);
  router.use("/orders/*", clerkAuthGuard);
  router.use("/vendors/*", clerkAuthGuard);
  router.use("/admin/*", clerkAuthGuard);
  router.use("/ledger/*", clerkAuthGuard);
  router.route("/auth", authRoutes);
  router.route("/catalog", catalogRoutes);
  router.route("/orders", orderRoutes);
  router.route("/vendors", vendorRoutes);
  router.route("/admin", adminRoutes);
  router.route("/ledger", ledgerRoutes);
  router.route("/storefront", storefrontRoutes);
  return router;
};
