import {
    IconAlertTriangle,
    IconArrowRight,
    IconBox,
    IconBrandGithub,
    IconBuildingStore,
    IconChartBar,
    IconCheck,
    IconChevronLeft,
    IconChevronRight,
    IconCommand,
    IconCreditCard,
    IconCrown,
    IconDashboard,
    IconDeviceLaptop,
    IconDots,
    IconFile,
    IconFileText,
    IconFolder,
    IconHelpCircle,
    IconLayoutDashboard,
    IconLayoutKanban,
    IconLoader2,
    IconLogin,
    IconLogout,
    IconMoon,
    IconPackage,
    IconPalette,
    IconPhoto,
    IconPlus,
    IconReceipt,
    IconSettings,
    IconShoppingCart,
    IconStar,
    IconSun,
    IconTags,
    IconTrash,
    IconTruck,
    IconUser,
    IconUserCircle,
    IconUserEdit,
    IconUsers,
    IconUserX,
    IconWallet,
    IconX,
    type IconProps,
} from "@tabler/icons-react";

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
    dashboard: IconLayoutDashboard,
    logo: IconCommand,
    login: IconLogin,
    logout: IconLogout,
    close: IconX,
    product: IconBox,
    palette: IconPalette,
    spinner: IconLoader2,
    kanban: IconLayoutKanban,
    chevronLeft: IconChevronLeft,
    chevronRight: IconChevronRight,
    trash: IconTrash,
    employee: IconUserX,
    post: IconFileText,
    page: IconFile,
    userPen: IconUserEdit,
    user2: IconUserCircle,
    media: IconPhoto,
    settings: IconSettings,
    billing: IconCreditCard,
    ellipsis: IconDots,
    add: IconPlus,
    warning: IconAlertTriangle,
    user: IconUser,
    arrowRight: IconArrowRight,
    help: IconHelpCircle,
    sun: IconSun,
    moon: IconMoon,
    laptop: IconDeviceLaptop,
    github: IconBrandGithub,
    check: IconCheck,
    workspace: IconFolder,
    teams: IconUsers,
    pro: IconCrown,
    exclusive: IconStar,
    account: IconUserCircle,
    profile: IconUser,
    orders: IconReceipt,
    inventory: IconPackage,
    payouts: IconWallet,
    analytics: IconChartBar,
    categories: IconTags,
    cart: IconShoppingCart,
    store: IconBuildingStore,
    shipping: IconTruck,
    tenants: IconFolder,
    ledger: IconCreditCard,
    users: IconUsers,
} as const;
